### ISSUE TITLE
PM 5 Issue

### ISSUE THREAD

**Issue by Shelly7w7** [ColinHDev/VanillaHopper#6] opened 2023-05-25 22:06 UTC
For some reason the hoppers are not working on the latest PM5 version. I have attached the details below:
![image](https://github.com/ColinHDev/VanillaHopper/assets/36070804/39111e5a-420c-4c63-88ef-afa9e519fff7)

https://github.com/ColinHDev/VanillaHopper/assets/36070804/0d7576ea-b8f5-49e0-b691-7173dddfb29b

**Comment by ColinHDev** [comment] 2023-05-27 22:22
I am not able to reproduce this :/

**Comment by ColinHDev** [comment] 2023-06-05 15:42
Yeah, sorry. I am currently a bit busy, so I didn't have enough time to work on this.
It looks like the problem comes not from the block but from the hopper item instance(s?) which still references PocketMine's hopper block instance. That's why the blocks only work after restarting the server but not after placing them

**Comment by IcyEndymion004** [comment] 2023-07-02 16:26
I can vouch for this not working

**Comment by ColinHDev** [comment] 2023-07-02 16:37
I know, that the plugin is not working properly. That's the reason this issue is still open

**Comment by ColinHDev** [comment] 2023-07-02 20:17
It should be fixed as of https://github.com/ColinHDev/VanillaHopper/releases/tag/v2.2.2

**Closed by ColinHDev** 2023-07-02 20:17 UTC
